spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EXAMPLE?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init.mode: always # Spring Boot >=v2.5.0